version: "2"

services:
  neo4j.nqc:
    container_name: neo4j.nqc
    image: agrdocker/agr_neo4j_env:develop
    volumes:
      - dbstore:/data
      - dbstore:/logs
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - esnet
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4096
  agr_qc:
    image: agrdocker/agr_qc_run:develop
    networks:
      - esnet
    environment:
     - NEO4J_NQC_HOST=neo4j.nqc
     - NEO4J_NQC_PORT=7687

networks:
  esnet:

volumes:
  dbstore:
driver: local
